[platformio]
default_envs = m5stack-basic

[env:m5stack-basic]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified@^0.2.17
    https://github.com/m5stack/M5Module-Stepmotor.git
build_flags =
    -DCORE_DEBUG_LEVEL=1
